import Form from "@/components/Form";
import Table from "@/components/Table";
import { deleteUser, getUsers } from "@/lib/Helper";
import { deleteAction, toggleChangeAction } from "@/redux/Reducer";
import Head from "next/head";
import { BiUserPlus,BiX,BiCheck } from 'react-icons/bi';
import { useQueryClient } from "react-query";
import { useDispatch, useSelector } from "react-redux";


export default function Home() {


  const visible = useSelector((state) => state.app.client.toggleForm)
  const deleteId = useSelector(state => state.app.client.deleteId)
  const queryclient = useQueryClient();
  const dispatch = useDispatch();

  const handler = () => {
    dispatch(toggleChangeAction())
  }

  const deletehandler = async () => {
    if (deleteId) {
      await deleteUser(deleteId);
      await queryclient.prefetchQuery('users', getUsers);
      await dispatch(deleteAction(null))
    }
  }

  const canclehandler = async () => {
    console.log('cancle');
    await dispatch(deleteAction(null))
  }

  return (
      <section>
        <Head>
          <title>CRUD Application</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="py-5">
          <h1 className="text-xl md:text-5xl text-center font-bold py-10">Employee Management</h1>

          <div className="container mx-auto flex justify-between py-5 border-b mb-1">
            <div className="left flex gap-3">
              <button onClick={handler} className="flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-800">
                Add Employee <span className="px-1"><BiUserPlus size={23} /></span>
              </button>
          </div>
          {deleteId ? DeleteComponent({ deletehandler, canclehandler }) : <></>}
          </div>

          {/* collapsable form */}
          {visible ? <Form></Form> : <></>}

          <div className="container mx-auto">
            {/* table */}
            <Table />
          </div>
        </main>
      </section>
  )
}


function DeleteComponent({deletehandler,canclehandler}) {
  return (
    <div className="flex gap-5">
      <button>Are You Sure?</button>
      <button onClick={deletehandler} className="flex bg-red-500 text-white px-4 py-2 border rounded-md hover:bg-rose-500 hover:border-red-500 hover:text-gray-50">Yes <span className='px-1'><BiX color='rgb(255 255 255)' size= {25}/></span></button>
      <button onClick={canclehandler} className="flex bg-green-500 text-white px-4 py-2 border rounded-md hover:bg-green-500 hover:border-green-500 hover:text-gray-50">No <span className='px-1'><BiCheck color='rgb(255 255 255)' size= {25}/></span></button>
    </div>
  )
}
